server:
  port: 1111

spring:
  mail:
    host: smtp.163.com
    username: beesevenhuace@163.com
    password: a123456789
    default-encoding: UTF-8


thread:
  pool:
    corePoolSize: 5
    maxPoolSize: 50
    queueCapacity: 1000
    keepAliveSeconds: 300